In [1]:
!pip install sweetviz

Collecting sweetviz
  Downloading sweetviz-2.1.4-py3-none-any.whl (15.1 MB)
     ---------------------------------------- 15.1/15.1 MB 2.1 MB/s eta 0:00:00
Collecting importlib-resources>=1.2.0
  Downloading importlib_resources-5.12.0-py3-none-any.whl (36 kB)
Requirement already satisfied: jinja2>=2.11.1 in c:\users\suchi\anaconda3\lib\site-packages (from sweetviz) (3.0.3)
Requirement already satisfied: numpy>=1.16.0 in c:\users\suchi\anaconda3\lib\site-packages (from sweetviz) (1.21.5)
Requirement already satisfied: matplotlib>=3.1.3 in c:\users\suchi\anaconda3\lib\site-packages (from sweetviz) (3.6.0)
Requirement already satisfied: pandas!=1.0.0,!=1.0.1,!=1.0.2,>=0.25.3 in c:\users\suchi\anaconda3\lib\site-packages (from sweetviz) (1.4.4)
Requirement already satisfied: tqdm>=4.43.0 in c:\users\suchi\anaconda3\lib\site-packages (from sweetviz) (4.64.1)
Requirement already satisfied: scipy>=1.3.2 in c:\users\suchi\anaconda3\lib\site-packages (from sweetviz) (1.9.3)
Requirement already satisfied: zipp>=3.1.0 in c:\users\suchi\anaconda3\lib\site-packages (from importlib-resources>=1.2.0->sweetviz) (3.8.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\suchi\anaconda3\lib\site-packages (from jinja2>=2.11.1->sweetviz) (2.1.2)
Requirement already satisfied: packaging>=20.0 in c:\users\suchi\anaconda3\lib\site-packages (from matplotlib>=3.1.3->sweetviz) (21.3)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\suchi\anaconda3\lib\site-packages (from matplotlib>=3.1.3->sweetviz) (1.4.2)
Requirement already satisfied: pyparsing>=2.2.1 in c:\users\suchi\anaconda3\lib\site-packages (from matplotlib>=3.1.3->sweetviz) (3.0.9)
Requirement already satisfied: cycler>=0.10 in c:\users\suchi\anaconda3\lib\site-packages (from matplotlib>=3.1.3->sweetviz) (0.11.0)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\suchi\anaconda3\lib\site-packages (from matplotlib>=3.1.3->sweetviz) (1.0.7)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\suchi\anaconda3\lib\site-packages (from matplotlib>=3.1.3->sweetviz) (2.8.2)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\suchi\anaconda3\lib\site-packages (from matplotlib>=3.1.3->sweetviz) (4.25.0)
Requirement already satisfied: pillow>=6.2.0 in c:\users\suchi\anaconda3\lib\site-packages (from matplotlib>=3.1.3->sweetviz) (9.2.0)
Requirement already satisfied: pytz>=2020.1 in c:\users\suchi\anaconda3\lib\site-packages (from pandas!=1.0.0,!=1.0.1,!=1.0.2,>=0.25.3->sweetviz) (2022.1)
Requirement already satisfied: colorama in c:\users\suchi\anaconda3\lib\site-packages (from tqdm>=4.43.0->sweetviz) (0.4.5)
Requirement already satisfied: six>=1.5 in c:\users\suchi\anaconda3\lib\site-packages (from python-dateutil>=2.7->matplotlib>=3.1.3->sweetviz) (1.16.0)
Installing collected packages: importlib-resources, sweetviz
Successfully installed importlib-resources-5.12.0 sweetviz-2.1.4

In [2]:
import pandas as pd

In [3]:
import sweetviz

train = pd.read_csv("train.csv")
test = pd.read_csv("test.csv")

In [4]:
train.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [5]:
test.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1461,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,...,120,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal
1,1462,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal
2,1463,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal
3,1464,60,RL,78.0,9978,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2010,WD,Normal
4,1465,120,RL,43.0,5005,Pave,NaN,IR1,HLS,AllPub,...,144,0,NaN,NaN,NaN,0,1,2010,WD,Normal

### Analyzing a Single Dataframe (and its optional target feature)

In [6]:
my_report = sweetviz.analyze([train, "Train"],target_feat='SalePrice')

                                             |          | [  0%]   00:00 -> (? left)

### Generate the report in html formate

In [7]:
my_report.show_html('Train_Report.html')

Report Train_Report.html was generated! NOTEBOOK/COLAB USERS: the web browser MAY not pop up, regardless, the report IS saved in your notebook/colab files.

### Comparing two dataframes (e.g. Test vs Training sets)

In [8]:
combined_report = sweetviz.compare([train, "Train"], [test, "Test"], "SalePrice")

                                             |          | [  0%]   00:00 -> (? left)

In [9]:
combined_report.show_html('Combined_Report.html')

Report Combined_Report.html was generated! NOTEBOOK/COLAB USERS: the web browser MAY not pop up, regardless, the report IS saved in your notebook/colab files.